export { default as LoginPage } from './auth/LoginPage.vue'
export { default as ForgotPage } from './auth/ForgotPage.vue'
export { default as A2FCodePage } from './auth/A2FCodePage.vue'
export { default as SettingPage } from './Setting/BillingPage.vue'
export { default as AccountPage } from './Setting/AccountPage.vue'
export { default as TeamPage } from './Setting/TeamPage.vue'
export { default as NotificationPage } from './Setting/NotificationPage.vue'
export { default as ProfilePage } from './Setting/ProfilePage.vue'
